assertion_user_result = {
    "image_url_prefix": "https://images.webdesigan.com/",
    "image_ids": [
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "Generation",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "truncation": 1.0,
                "seed": "1234",
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "Generation",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "truncation": 1.0,
                "seed": "",
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "StyleMix",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "row_image": "1234",
                "column_image": "5678",
                "styles": "Fine",
                "truncation": 1.0,
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "StyleMix",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "row_image": "1234",
                "column_image": "5678",
                "styles": "Fine",
                "truncation": 1.0,
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "StyleMix",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "row_image": "1234",
                "column_image": "5678",
                "styles": "Fine",
                "truncation": 1.0,
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "StyleMix",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "row_image": "1234",
                "column_image": "image_id",
                "styles": "Middle",
                "truncation": 1.0,
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "StyleMix",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "row_image": "1234",
                "column_image": "image_id",
                "styles": "Middle",
                "truncation": 1.0,
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "StyleMix",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "row_image": "image_id",
                "column_image": "1234",
                "styles": "Coarse",
                "truncation": 1.0,
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "StyleMix",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "row_image": "image_id",
                "column_image": "1234",
                "styles": "Coarse",
                "truncation": 1.0,
            },
        },
        {
            "url": "this_is_hex_uid",
            "auth0_id": "007",
            "creation_date": "2020-02-02T20:20:20",
            "method": {
                "name": "StyleMix",
                "model": {"img": 31, "res": 256, "fid": 12, "version": "StyleGan2ADA"},
                "row_image": "image_id_1",
                "column_image": "image_id_2",
                "styles": "Coarse",
                "truncation": 1.0,
            },
        },
    ],
}
